version: "3.4"
services:
  app:
    build: .
    command: "cargo make api"
    volumes:
      - .:/var/www
      - /var/www/target
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/postgres?sslmode=disable
      - SECURE_COOKIE=false
      - ALLOWED_ORIGIN=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  client:
    build: ./apps/client
    command: "yarn start"
    volumes:
      - ./apps/client:/var/www
      - /var/www/node_modules
    environment:
      - REACT_APP_API_HOST=http://localhost:5000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
